on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

permissions: {}
jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: "true"
          body: |
            Please refer to [CHANGELOG.md](https://github.com/chandq/mock-service-cli/blob/master/CHANGELOG.md) for details.
